feat(uneditable): Adds linting for editable dashboards
grafana/dashboard-linter pull request #155
Opened 2023-10-17 03:57 UTC by xorima

# Description

Today this linter tests a number of settings, but it does not validate that the dashboard cannot be edited after it is deployed in the UI. If this linter is to ensure the source of truth for linted dashboards are a json code object, we should ensure they are not editable by default after deployment.

## Issues Resolved

resolves #151 

## Check List

- [x] New functionality includes testing.

2023-10-17 04:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/dashboard-linter?pullRequest=155) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/dashboard-linter?pullRequest=155) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/dashboard-linter?pullRequest=155) it.</sub>

2023-11-14 21:34 UTC, rgeyer requested changes
Thank you for the contribution, and for adding an autofix function also.

This needs a couple small tweaks in order to compile, and for the new rule to be part of the default ruleset.

Once those changes are made, I'll be happy to merge this PR.

Thank you again!

2023-11-14 21:34 UTC, rgeyer commented on lint/rule_uneditable.go
> +			if d.Editable {
Editable needs to be added as a field to the `Dashboard` struct in `lint.go`

2023-11-14 21:34 UTC, rgeyer commented on lint/rule_uneditable_test.go
> +	linter := NewUneditableRule()
The new rule needs to be added to the default ruleset in `rules.go`

2023-11-16 04:54 UTC, xorima commented
@rgeyer I've pushed up the fixes as requested. 

Note also golangci is having some warnings so raised #161  for it and may throw in a pr later today to do as it recomments

2023-12-14 10:03 UTC, xorima commented
@rgeyer @tomwilkie any updates on this one?

2024-07-10 16:13 UTC, rgeyer approved these changes

2024-07-10 16:14 UTC, rgeyer commented
> @rgeyer @tomwilkie any updates on this one?

Sorry for the unacceptably long delay here, getting this merged now.

2024-07-10 16:14 UTC, merged